# Generated by Django 5.0.6 on 2024-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.FloatField()),
                ("carbon_footprint", models.FloatField()),
                ("unit", models.CharField(default="kg", max_length=10)),
            ],
        ),
    ]
