# Generated by Django 5.0.6 on 2024-07-07 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migrate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="carbon_footprint",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="quantity",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="unit",
            field=models.CharField(
                choices=[("kg", "Kilogram"), ("L", "Liter"), ("枚", "Pieces")],
                default="kg",
                max_length=10,
            ),
        ),
    ]
