# Generated by Django 5.0.6 on 2024-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migrate", "0002_alter_food_carbon_footprint_alter_food_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
